#!/usr/bin/env python3
#
# character-attributes.py
#
# Include in pandas or Jupyter notebook to create a `character attributes`
# dataframe looking like this:
#
#                  | species        | sex        |
#                  | (species_type) | (sex_type) |
#   ---------------+----------------+------------+
#    Julian Bashir | Human          | Male       |
#    Elim Garak    | Cardassian     | Male       |
#
# That dataframe can then be intersected with other dataframes to
# add species and sex columns.
#
# Copyright © Wey Turner, 2022.
# SPDX-License-Identifier: GPL-2.0-only

import pandas as pd

sex_type = pd.api.types.CategoricalDtype(
    categories=[
        'Male',
        'Female',
        'Other',
        'unknown'
    ],
    ordered=True)

species_type = pd.api.types.CategoricalDtype(
    categories=[
        'Bajoran',
        'Betazoid',
        'Cardassian',
        'Cat',
        'Changeling',
        'Ferangi',
        'Hologram',
        'Human',
        "Jem'Hadar",
        'Klingon',
        'Q',
        'Romulan',
        'Symbiont'
        'Trill',
        'Vorta',
        'Vulcan',
        'unknown'
    ],
    ordered=True)

character_attributes = pd.DataFrame.from_dict({
    "Darhe'el": ['Cardassian', 'Male'],
    "Dukat's Children": ['Cardassian', 'unknown'],
    "Dukat's Mother": ['Cardassian', 'Female'],
    "K'Ehleyr": ['Klingon', 'Female'],
    "Keiko O’Brien": ['Human', 'Female'],
    "Kirayoshi O'Brien": ['Human', 'Male'],
    "Kotan Pa'Dar": ['Cardassian', 'Male'],
    "Miles O'Brien": ['Human', 'Male'],
    "Molly O'Brien": ['Human', 'Female'],
    "Omet'iklan": ["Jem'Hadar", 'Male'],
    "Remata'Klan": ["Jem'Hadar", 'Male'],
    "Rugal Pa'Dar": ['Cardassian', 'Male'],
    'Aamin Marritza': ['Cardassian', 'Male'],
    'Akellen Macet': ['Cardassian', 'Male'],
    'Akorem Laan': ['Bajoran', 'Male'],
    'Alexander Rozhenko': ['Human', 'Male'],
    'Alynna Nechayev': ['Human', 'Female'],
    'Amsha Bashir': ['Human', 'Female'],
    'Arjin': ['Trill', 'Male'],
    'Athra Dukat': ['Cardassian', 'Female'],
    'Audrid Dax': ['Trill', 'Female'],
    'Baby Changeling': ['Changeling', 'unknown'],
    'Bareil Antos': ['Bajoran', 'Male'],
    'Barin Troi': ['Betazoid', 'Male'],
    'Benjamin Sisko': ['Betazoid', 'Male'],
    'Broca': ['Cardassian', 'Male'],
    'Brunt': ['Ferangi', 'Male'],
    'Cal Hudson': ['Human', 'Male'],
    'Captain Solok': ['Vulcan', 'Male'],
    'Chalan Aroya': ['Bajoran', 'Female'],
    'Chester': ['Cat', 'Male'],
    'Corat Damar': ['Cardassian', 'Male'],
    'Corbin Entek': ['Cardassian', 'Male'],
    'Curzon Dax': ['Trill', 'Male'],
    'Dax': ['sy', 'Other'],
    'Dulmur': ['Human', 'Male'],
    'Elim Garak': ['Cardassian', 'Male'],
    'Emergency Medical Hologram Mark II': ['Hologram', 'Male'],
    'Emony Dax': ['Trill', 'Female'],
    'Enabran Tain': ['Cardassian', 'Male'],
    'Entek': ['Cardassian', 'Male'],
    'Eris': ['Vorta', 'Female'],
    'Ezri Dax': ['Trill', 'Female'],
    'Fala Trentin': ['Bajoran', 'Female'],
    'Female Changeling': ['Changeling', 'Female'],
    'Furel': ['Bajoran', 'Male'],
    'Gaila': ['fc', 'Male'],
    'Gariff Lucsly': ['Human', 'Male'],
    'Gilora Rejal': ['Cardassian', 'Female'],
    'Gowron': ['Klingon', 'Male'],
    'Grilka': ['Klingon', 'Female'],
    'Gul Jasad': ['Cardassian', 'Male'],
    'Gul Marratt': ['Cardassian', 'Male'],
    'Gul Revok': ['Cardassian', 'Male'],
    'Gul Rusot': ['Cardassian', 'Male'],
    'Gul Russol': ['Cardassian', 'Male'],
    'Gul Zarale': ['Cardassian', 'Male'],
    'Iliana Ghemor': ['Cardassian', 'Female'],
    'Iloja of Prim': ['Cardassian', 'Male'],
    'Ishka': ['Ferangi', 'Female'],
    'Jack': ['Human', 'Male'],
    'Jadzia Dax': ['Trill', 'Female'],
    'Jake Sisko': ['Human', 'Male'],
    'Jaro Essa': ['Bajoran', 'Male'],
    'Jennifer Sisko': ['Human', 'Female'],
    'Joran Dax': ['Trill', 'Male'],
    'Joseph Sisko': ['Human', 'Male'],
    'Judith Sisko': ['Human', 'Female'],
    'Julian Bashir': ['Human', 'Male'],
    'Kai Winn': ['Bajoran', 'Female'],
    'Kang': ['Klingon', 'Male'],
    'Kasidy Yates': ['Human', 'Male'],
    'Keevan': ['Vorta', 'Male'],
    'Kelas Parmak': ['Cardassian', 'Male'],
    'Keldar': ['Ferangi', 'Male'],
    'Kilana': ['Vorta', 'Female'],
    'Kimara Cretak': ['Romulan', 'Female'],
    'Kira Meru': ['Bajoran', 'Female'],
    'Kira Nerys': ['Bajoran', 'Female'],
    'Kira Pohl': ['Bajoran', 'Male'],
    'Kira Reon': ['Bajoran', 'Male'],
    'Kira Taban': ['Bajoran', 'Male'],
    'Koloth': ['Klingon', 'Male'],
    'Kor': ['Klingon', 'Male'],
    'Kurn': ['Klingon', 'Male'],
    'Laas': ['Changeling', 'Male'],
    'Lauren': ['Human', 'Female'],
    'Leeta': ['Bajoran', 'Female'],
    'Lela Dax': ['Trill', 'Female'],
    'Lenara Kahn': ['Trill', 'Female'],
    'Lewis Zimmerman': ['Human', 'Male'],
    'Leyton': ['Human', 'Male'],
    'Li Nalas': ['Bajoran', 'Male'],
    'Lisa Cusak': ['Human', 'Female'],
    'Lupaza': ['Bajoran', 'Female'],
    'Luther Sloan': ['Human', 'Male'],
    'Lwaxana Troi': ['Betazoid', 'Female'],
    'Martok': ['Klingon', 'Male'],
    'Michael Eddington': ['Human', 'Male'],
    'Mila Garak': ['Cardassian', 'Female'],
    'Mora Pol': ['Bajoran', 'Male'],
    'Morn': ['unknown', 'Male'],
    'Mullibok': ['Bajoran', 'Male'],
    'Natima Lang': ['Bajoran', 'Male'],
    'Niala Damar': ['Cardassian', 'Female'],
    'Nilani Kahn': ['Trill', 'Female'],
    'Nog': ['Ferangi', 'Male'],
    'Odo': ['Changeling', 'Male'],
    'Opaka': ['Bajoran', 'Female'],
    'Patrick': ['Human', 'Male'],
    'Pel': ['Ferangi', 'Female'],
    'Prinadora': ['Ferangi', 'Female'],
    'Q': ['Q', 'Male'],
    'Quark': ['Ferangi', 'Male'],
    'Rebecca Sisko': ['Human', 'Female'],
    'Rebecca Sullivan': ['Human', 'Female'],
    'Richard Bashir': ['Human', 'Male'],
    'Rom': ['Ferangi', 'Male'],
    'Sakal Damar': ['Cardassian', 'Male'],
    'Sarah Sisko': ['Human', 'Female'],
    'Sarina Douglas': ['Human', 'Female'],
    'Shakaar Edon': ['Bajoran', 'Male'],
    'Sirella': ['Klingon', 'Female'],
    'Skrain Dukat': ['Cardassian', 'Male'],
    'Tahna Los': ['Bajoran', 'Male'],
    'Tekeny Ghemor': ['Cardassian', 'Male'],
    'Thomas Riker': ['Human', 'Male'],
    'Thrax': ['Cardassian', 'Male'],
    'Tobin Dax': ['Trill', 'Male'],
    'Tora Naprem': ['Cardassian', 'Female'],
    'Tora Ziyal': ['Multiple', 'Female'],
    'Torias Dax': ['Trill', 'Male'],
    'Vaatrik Pallra': ['Bajoran', 'Female'],
    'Vash': ['Human', 'Female'],
    'Verad': ['Trill', 'Male'],
    'Vic Fontaine': ['Human', 'Male'],
    'Vreenak': ['Romulan', 'Male'],
    'Weyoun': ['Vorta', 'Male'],
    'Winn Adami': ['Bajoran', 'Female'],
    'Worf': ['Klingon', 'Male'],
    'Yedrin Dax': ['Trill', 'Male'],
    'Yelgrun': ['Vorta', 'Male'],
    'Zek': ['Ferangi', 'Male'],
    'Ziranne Idaris': ['Trill', 'Female']},
                                              orient='index',
                                              columns=['species', 'sex'],
                                              dtype='string')
# Species and Sex are categories
character_attributes['species'] = character_attributes['species'].astype(species_type)
character_attributes['sex'] = character_attributes['sex'].astype(sex_type)

# character_attributes is ready for use
